@startuml Adapter Pattern

class client{

}
interface Target{
    + void request()
}

client -> Target

class Adapter implements Target{
    + void request()
}

class Adaptee{
    + void specificRequest()
}
Adapter -> Adaptee
@enduml
