@startuml Adapter Pattern

class client{

}
class Target{
    + virtual void request()
}

client -> Target

class Adapter implements Target{
    - Adaptee* m_adptee
    + void request()
}

class Adaptee{
    + void specificRequest()
}
Adapter -> Adaptee
@enduml
