@startuml Facade Pattern
' 使用单个外观类隔离多重依赖
class Client{

}
class Facade{

}
Client -> Facade

package "sub system, including lots of interface"{
    class A
    class B
    class C
    class D
    
    A - B
    B - C
    C - D
    B - D
    A -> Facade
    B -> Facade
}
@enduml
