@startuml Strategy Pattern
package "客户"{
class Duck
{
    - FlyBehavior m_flyBehavior
    - QuackBehavior m_quackBehavior
    --
    + void display()
    + void performFly()
    + void performQuack()
    + void setFlyBehavior()
    + void setQuackBehavior()
    // 鸭子的其他行为...
}



class MallarDuck extends Duck{
    +void display()
}
class RedheadDuck extends Duck{
    +void display()
}
class RubberDuck extends Duck{
    +void display()
}
class DecoyDuck extends Duck{
    +void display()
}
}
package "封装飞行行为" {
Duck -->FlyBehavior
interface FlyBehavior{
    +void fly()
}


class FlyWithWings implements FlyBehavior{
    void fly()
}
class FlyNoway implements FlyBehavior{
    void fly()
}
class FlynewWay implements FlyBehavior{
    void fly()
}
}

package "封装呱呱叫行为"{
Duck -->QuackBehavior

interface QuackBehavior{
    + void quack()
}
class SimpleQuack implements QuackBehavior{
    + void quack() {// 实现SimpleQuack}
}
class Mute implements QuackBehavior{
    + void quack() {// do noting.}
}

}
@enduml

