@startuml Template Method Pattern
abstract class CaffeineBeverage{
    + void prepareRecipe() final  // template method
    + void boilWater()
    + void pourInCup()
    + <color:blue>virtual void brew()   
    + <color:blue>virtual void addCondiments()  
    + <color:blue>bool CustomerWantCondiments()   // hook method
}
' brew: brew sth, to make a hot drink of tea or coffee

class Coffe extends CaffeineBeverage{
    + <color:blue>void brew() 
    + <color:blue>void addCondiments()  
    + <color:blue>CustomerWantCondiments() 
}

class Tea extends CaffeineBeverage{
    + <color:blue>void brew() 
    + <color:blue>void addCondiments() 
    + <color:blue>CustomerWantCondiments() 
}

@enduml